server:
  servlet:
    encoding:
      charset: utf-8
      force: true
  port: 8080

spring:
  mustache:
    servlet:
      expose-session-attributes: true  # Mustache ????? ?? ??? ??? ? ??? ??
      expose-request-attributes: true  # Mustache ????? ?? ??? ??? ? ??? ??
  datasource:
    driver-class-name: org.h2.Driver    # ?????? ????? H2 DB? ??
    url: jdbc:h2:mem:test;MODE=MySQL    # H2 ???? ??????? MySQL ?? ??? ?? (????)
    username: sa                        # ?????? ?? ? ?? ??? ??
    password:                           # ?????? ?? ???? (?? ??)
  h2:
    console:
      enabled: true   # H2 ?????? ??? ????? ?????? ??????? ??? ? ??? ?
  sql:
    init:
      schema-locations: classpath:db/schema.sql  # ??? ?? SQL ?? ??
      data-locations: classpath:db/data.sql      # ??? ?? SQL ?? ??
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:/mapper/*.xml  # MyBatis ?? XML ?? ??

  output:
    ansi:
      enabled: always  # ?? ?? ? ANSI ??? ?? ????? ?? (??? ?? ??? ? ?? ?? ??)
      encoding:
        force-response: true

payments:
  toss:
    test_client_api_key : test_ck_DnyRpQWGrNqpzLg1DZKOVKwv1M9E
    test_secret_api_key : test_ck_DnyRpQWGrNqpzLg1DZKOVKwv1M9E

